"""initial schema

Revision ID: 9732aaf39934
Revises: 
Create Date: 2026-10-04 17:48:24.751794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9732aaf39934'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('log_return', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_ticker_date')
    )
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.create_index('ix_ticker_date', ['ticker', 'date'], unique=False)

    op.create_table('portfolio_header',
    sa.Column('portfolio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_name', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('portfolio_name')
    )
    op.create_table('portfolio_composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('date_established', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_header.portfolio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_id_ticker')
    )
    with op.batch_alter_table('portfolio_composition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_composition_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_composition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_composition_id'))

    op.drop_table('portfolio_composition')
    op.drop_table('portfolio_header')
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.drop_index('ix_ticker_date')

    op.drop_table('historical_data')
    # ### end Alembic commands ###
