"""Portfolio tables modified

Revision ID: b4b195ca1570
Revises: 9732aaf39934
Create Date: 2026-10-06 22:33:03.551716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b195ca1570'
down_revision: Union[str, Sequence[str], None] = '9732aaf39934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_composition', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('portfolio_header', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_portfolio_name', ['portfolio_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_header', schema=None) as batch_op:
        batch_op.drop_constraint('uq_portfolio_name', type_='unique')

    with op.batch_alter_table('portfolio_composition', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
